In [ ]:
from placy import PLACy
import pandas as pd

#import data from a csv file, convert it to numpy array 
data = pd.read_csv("example.csv").to_numpy()

#run PLACy 
cm = PLACy(data, max_lags=10, window_length=50, stride=1,use_bh_fdr = True, acyclicity = True)

#causal matrix [cause,effect] = 1
print(cm)

[[0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
