In [ ]:
from placy import PLACy
import pandas as pd


#The input CSV should contain a multivariate time series with shape n_timesteps × n_variables
#where each column corresponds to a variable and each row corresponds to a timestamp.

#import data from a csv file, convert it to numpy array 
data = pd.read_csv("example.csv").to_numpy()

#run PLACy 
cm = PLACy(data, max_lags=10, window_length=50, stride=1,use_bh_fdr = True, acyclicity = True)

#use_bh_fdr = True → Benjamini-Hochberg procedure applied to control the false discovery rate when performing multiple hypothesis tests, which is common in causality detection tasks.
#acyclicity = True → ensures that the resulting causality matrix does not contain cycles,

#causal matrix [cause,effect] = 1
print(cm)

[[0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
