In [ ]:
from placy import PLACy
import pandas as pd


#The input CSV should contain a multivariate time series with shape n_timesteps × n_variables
#where each column corresponds to a variable and each row corresponds to a timestamp.

#import data from a csv file, convert it to numpy array 
data = pd.read_csv("example.csv").to_numpy()

#run PLACy 
cm = PLACy(data.T, max_lags=10, window_length=50, stride=1,use_bh_fdr = True, acyclicity = True)

#use_bh_fdr = True → Benjamini-Hochberg procedure applied to control the false discovery rate when performing multiple hypothesis tests, which is common in causality detection tasks.
#acyclicity = True → ensures that the resulting causality matrix does not contain cycles,

#causal matrix [cause,effect] = 1
print(cm)

[[1.         1.         1.         1.         1.        ]
 [1.00290048 0.9375476  1.02164142 1.00408669 1.0459427 ]
 [0.92700393 1.15914025 0.95919462 0.95828732 1.035796  ]
 ...
 [1.59016106 2.89391542 4.22383925 2.07780837 3.40570062]
 [1.18864948 2.92988273 4.03546247 2.20002727 3.73475683]
 [1.48572775 3.06766196 3.54017127 2.10138456 3.96225538]]
[[0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


: 